name: Terraform client CI

permissions:
  contents: write
  packages: write

on:
  push:
    branches-ignore:
      - master
      - bugfix/inputs-issue
  pull_request:
    branches:
      - master
  workflow_dispatch:
    inputs:
      confirm_action:
        description: "Type 'yes' if you want to create a new tag"
        required: true
        default: "no"

jobs:
  build_package:
    uses: cyberrangecz/actions-templates/.github/workflows/python_build_template.yml@bugfix/inputs-issue
    secrets:
      PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
    with:
      publish_and_tag: ${{ github.event.inputs.confirm_action }}
